{
 "title": "Registrations",
 "description": "KPIs regarding user registration",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Users Registered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select date(date) as time, count(id) as \"Raw Registrations\" from \"user\" group by date(date) order by date(date);"
    },
    {
     "rawSql": "select date(date) as time, count(id) as \"Returning Users\" from \"user\" where logins > 0 and date_part('day', last_login::timestamp - date::timestamp) > 0 group by date(date) order by date(date);"
    }
   ]
  },
  {
   "title": "Number of edits of recently registered users (if any)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select \"user\".date as time, count(actor_id) as \"Edits\" from \"user\" join event_log on date_part('day', CURRENT_DATE - \"user\".date) between 0 and 90 and \"user\".id = event_log.actor_id and event_id in (4,5) group by \"user\".id;"
    }
   ]
  },
  {
   "title": "User Registrations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, count(id) as \"Returning Users\" from \"user\" where logins > 0 and date_part('day', last_login::timestamp - date::timestamp) > 0;"
    },
    {
     "rawSql": "select now() as time, \n  count(id) \n    - (select count(id) as \"Returning Users\" from \"user\" where logins > 0 and date_part('day', last_login::timestamp - date::timestamp) > 0)\n  \nas \"Raw Registrations\" from \"user\";"
    }
   ]
  },
  {
   "title": "Author Registrations",
   "type": "grafana-piechart-panel",
   "description": "Registered users with at least one edit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, \n  count(id) \n    - (select count(distinct \"user\".id) as \"Authors\" from \"user\" join event_log on actor_id = \"user\".id)\n  \nas \"Raw Registrations\" from \"user\";"
    },
    {
     "rawSql": "select now() as time, count(distinct \"user\".id) as \"Authors\" from \"user\" join event_log on actor_id = \"user\".id;"
    }
   ]
  }
 ]
}