{
 "title": "Reviewing",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "cached_days", "label": "Zeitraum für Reviewzeiten", "query": "90,7,1" },
   {
    "name": "active_edits_since",
    "query": " select to_char(max(time) - interval '90 day', 'DD. Mon YYYY') from cache_author_edits_by_category;"
   }
  ]
 },
 "panels": [
  {
   "title": "Reviewzeiten in den jeweils letzten [[cached_days]] Tagen",
   "type": "graph",
   "description": "Dieses Dashboard zeigt die Reviewzeiten in Stunden an. Gezählt werden alle Bearbeitungen der letzten 90 Tagen sowie alle ungereviewten Bearbeitungen. Bearbeitungen von Autor*innen mit Review-Rechten werden nicht gezählt:\n\n* Median: 50% der Bearbeitungen wurden schneller gereviewt\n* 75%-Perzentil: 75% der Bearbeitungen wurden schneller gereviewt\n* 95%-Perzentil: 95% der Bearbeitungen wurden schneller gereviewt",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Stunden" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  EXTRACT(epoch FROM perc_50)/3600 as \"Median (h)\",\n  EXTRACT(epoch FROM perc_75)/3600 as \"75%-Perzentil (h)\",\n  EXTRACT(epoch FROM perc_95)/3600 as \"95%-Perzentil (h)\"\nFROM\n  cache_review_time[[cached_days]]\nWHERE\n  $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Anzahl Reviewer*innen",
   "type": "graph",
   "description": "Verlauf der Anzahl von Reviewer*innen: Gezählt werden nur Bearbeitungen der jeweils letzten 90 Tage. Nur manuelle Reviewing-Aktionen (Annahme und Ablehung) *fremder Bearbeitungen* werden betrachtet:\n\n* Reviewer*in: Mindestens ein Reviewing in den letzten 90 Tagen\n* Aktive Reviewer*innen: Mindestens 10 Reviewing-Aktionen in den letzten 90 Tagen\n* Aktive Reviewer*innen: Mindestens 100 Reviewing-Aktionen in den letzten 90 Tagen",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Anzahl" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  reviewers as \"Reviewer*innen\",\n  active_reviewers as \"Aktive Reviewer*innen\",\n  very_active_reviewers as \"Sehr aktive Reviewer*innen\"\nFROM cache_active_reviewers\nWHERE $__timeFilter(time) ORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Aktive Reviewer pro Fach (mehr als 10 Reviews in den letzten 90 Tagen)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select username as \"Username\", review_count as \"Reviews seit [[active_edits_since]]\" from cache_author_reviews inner join \"user\" on \"user\".id = cache_author_reviews.author where review_count >= 10 and cache_author_reviews.time = (select max(time) from cache_author_reviews) order by username;"
    }
   ]
  },
  {
   "title": "Verlauf Reviewzeiten (in Stunden)",
   "type": "heatmap",
   "description": "Dieses Dashboard zeigt den Verlauf der Verteilung der Reviewzeiten in Stunden an. Zunächst wird die Zeit in verschiedene Zeiträume unterteilt. In jedem Zeitraum wird die Verteilung der Review-Zeiten durch Farben angegeben. Je transparenter ein Block ist, desto weniger Bearbeitungen in diesem Zeitraum haben entsprechende Reviewzeiten. Die Y-Achse ist dabei logarithmisch zur Basis 2 und in Stunden angegeben.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(el1.date) AS time,\n  ceiling(EXTRACT(epoch FROM el2.date - el1.date) / 3600) AS \"Reviewzeit\"\nFROM event_log el1\nINNER JOIN event_log el2 \nON\n  el1.uuid_id = el2.uuid_id AND\n  el2.date >= el1.date AND\n  (el2.event_id = 6 OR el2.event_id = 11) AND\n  $__timeFilter(el1.date) AND\n  el1.event_id = 5\nWHERE\n  el1.actor_id != el2.actor_id;"
    }
   ]
  },
  {
   "title": "Bearbeitungen pro Tag",
   "type": "graph",
   "description": "Bearbeitungen pro Tag sortiert nach folgenden Kategorien:\n\n* Selbstreview: Beareitungen von Autor*innen mit Review-Rechten.\n* Fremdreview: Bearbeitung wurde von einer anderen Person im Reviewverfahren akzeptiert oder abgelehnt.\n* Ohne Review: Für diese Bearbeitung liegt kein Reviewing vor. Dies liegt daran, dass entweder die Bearbeitung noch offen ist oder eine darauffolgende Bearbeitung gereviewt wurde.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Anzahl" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(el1.date) AS time,\n  count(el1.id) AS \"Selbstreview\"\nFROM event_log el1\nLEFT OUTER JOIN event_log el2\nON\n  el1.uuid_id = el2.uuid_id AND\n  el2.date >= el1.date AND\n  el1.event_id = 5 AND\n  (el2.event_id = 6 OR el2.event_id = 11) AND\n  $__timeFilter(el1.date)\nWHERE\n  el1.actor_id = el2.actor_id AND\n  $__timeFilter(el1.date)\nGROUP BY DATE(el1.date)\nORDER BY DATE(el1.date);"
    },
    {
     "rawSql": "SELECT\n  DATE(el1.date) AS time,\n  count(el1.id) AS \"Fremdreview\"\nFROM event_log el1\nINNER JOIN event_log el2\nON\n  el1.uuid_id = el2.uuid_id AND\n  el2.date >= el1.date AND\n  el1.event_id = 5 AND\n  (el2.event_id = 6 or el2.event_id = 11) AND\n  $__timeFilter(el1.date)\nWHERE\n  el1.actor_id != el2.actor_id AND\n  $__timeFilter(el1.date)\nGROUP BY DATE(el1.date) ORDER BY DATE(el1.date);"
    },
    {
     "rawSql": "SELECT\n  DATE(el1.date) as time,\n  count(el1.id) as \"Ohne Review\"\nFROM event_log el1\nLEFT OUTER JOIN event_log el2\nON\n  el1.uuid_id = el2.uuid_id AND\n  el2.date > el1.date AND\n  el1.event_id = 5 AND\n  el1.date > '2015-01-01'\nWHERE\n  el2.event_id is null AND\n  $__timeFilter(el1.date)\nGROUP BY DATE(el1.date) ORDER BY DATE(el1.date);\n"
    }
   ]
  }
 ]
}