{
 "title": "Author Activity",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Reviewzeiten in den letzten 90 Tagen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Stunden" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  EXTRACT(epoch FROM perc_50)/3600 as \"Median (h)\",\n  EXTRACT(epoch FROM perc_75)/3600 as \"75%-Perzentil (h)\",\n  EXTRACT(epoch FROM perc_95)/3600 as \"95%-Perzentil (h)\"\nFROM\n  cache_review_time\nWHERE\n  $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Anzahl Autor*innen (insgesamt)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Anzahl" }
   ],
   "targets": [
    {
     "rawSql": "select * from cache_active_authors WHERE $__timeFilter(time) ORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Anzahl Autor*innen (pro Fach)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Anzahl" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  cache_edits_by_category\nWHERE\n  $__timeFilter(time)\nORDER BY time ASC;\n"
    }
   ]
  }
 ]
}