{
 "title": "Registrations",
 "description": "KPIs regarding user registration",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Users Registered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select date as time, count(id) as \"Raw Registrations\" from (select str_to_date(concat(day(date),'-',month(date),'-',year(date)), '%d-%m-%Y') as date, id from user) u group by date;"
    },
    {
     "rawSql": "select date as time, count(id) as \"Returning Users\" from (select str_to_date(concat(day(date),'-',month(date),'-',year(date)), '%d-%m-%Y') as date, id from user where logins > 0 and datediff(last_login, date) > 0) u group by date;"
    }
   ]
  },
  {
   "title": "Number of edits of recently registered users (if any)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "select user.date as time, count(actor_id) as \"Edits\" from user join event_log on datediff(now(), user.date) between 0 and 90 and user.id = event_log.actor_id and event_id in (4,5) group by user.id;"
    }
   ]
  },
  {
   "title": "User Registrations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, count(id) as \"Returning Users\" from serlo.user where logins > 0 and datediff(last_login, date) > 0;"
    },
    {
     "rawSql": "select now() as time, \n  count(id) \n    - (select count(id) as \"Returning Users\" from serlo.user where logins > 0 and datediff(last_login, date) > 0)\n  \nas \"Raw Registrations\" from serlo.user;"
    }
   ]
  },
  {
   "title": "Author Registrations",
   "type": "grafana-piechart-panel",
   "description": "Registered users with at least one edit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select now() as time, \n  count(id) \n    - (select count(distinct user.id) as \"Authors\" from serlo.user join event_log on actor_id = user.id)\n  \nas \"Raw Registrations\" from serlo.user;"
    },
    {
     "rawSql": "select now() as time, count(distinct user.id) as \"Authors\" from serlo.user join event_log on actor_id = user.id;"
    }
   ]
  }
 ]
}